spring:
  datasource:
    url: jdbc:mysql://localhost:3306/figures
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 5000
        max-page-size: 10000
  liquibase:
    change-log: db/db.changelog-master.xml
    enabled: true
    drop-first: true